spring.application.name=floor-is-lava-backend

spring.datasource.url=jdbc:postgresql://ep-damp-scene-a16fj0b2-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=86400000

server.port=${PORT:8081}